travis:
  secure:
    BINSTAR_TOKEN: kmDmphYPnvkbNipG2zgt/uME2LwkvzUSiiA0/bTGARF8KWgbW9sNoLQGLkzke0Uc1VjAwyuXkrx+PzbgFg2ixqG19NmwgunuHvhVHK7hV8JDt3RsVi1H1m/MkcWSDIEz09fCbZg9rCNU6NSqqoV24HqGw4PqxAACX2t8HXWw4UYBtVVCo7YzegxoxGkZcf10KX/yIz80nX10OJxjYVlFvILkWQHCCgSRBS2JVJfT5/0oHs495+FIewTesMQKuUiUgw2n3yHNk2cUBl1QoBtucsNktDIVLCWnbSARroVU/Edp4Ew3/ZFJiQLWdTzXBQSXxeq2fp/LspvcYtPe7dB6CLcHWCeQqWP7zqp9SM25XzLZQOReFEPTFmkwfbPKi7nbgyXQnRMzGVgPFXwAJbvASgwtYge6EKcUYEt+4FSl9dbsgPYomMaH4zgeyveWdl8sc9b4F281R6pk//58yzcXOp5pmbR3zuNwfV4qirNqA+7JGhJCtu80UX0TQD0761IlhCANUrjVlWCp+LZnEx6KRZ/4XSmfOyIwNISaREr3Jb55xUuH3LLd9KMrJQaoYV6sv9DaJvwmg3/11RjSl+j1qcGd/OHD+4Wa5zBg43Cl6/bhFMkf5cmb/w4FFE8v1feBElWPbJsWchIk5gi0CSEUqIc3m/eAjghDwtnIR6rbwFo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
