travis:
  secure:
    BINSTAR_TOKEN: KYhMlmxKu1Ly/Yg/UeOboj1FK45aj7k0+l5gU675jWzUR//jB3ddXI/TV4Tkgj53A9IBdRFjFMg4/C72EtOJGAkIMYwUZYzozZioPcCV/FJeXjOsQNKMW27tFuXAuswjdYrGFQ9SZVfeW0e2yu39mH7mv2H7YW7t+n/gw2VoHt891hivR/SfMoh4mVLD6K+EL1B1tNaSysCuVsA18zoZFpVPtQt3P1GHjiBm7AiQqwzmUQbU72i0jg2Okm/TWRVTbw6cFREn1dd51gFlAyJvzzTewgMuVamgk97KB7wtCHEMwYMm6a2dGCRB6hSM48GzQ9/mmZ9RbcarQgk54gUHnl/B2FCN0yjxGu90Tv90OCAet1GUEdRz7VFfhvNYPGeJzhCS9Y3BluGmSYLLmqfOc01gdmDEXRloZa2EOeCDIzL87g5uxcgmV8+E1uF/kRvvWUnzqCUwTDxmSxYOlDh6oBWA25mO5U98GpXHghIetoxoNcUWMZnZoWYdB0jUwMuHHovB59PtCp0vqonV4HvnL3tXILmxM8h96c1TBQ4fxSGYfZpGXVL2Wl0oE+EEPrfVtjGVYmq76psKBJGTQLaEUyRtVgu3lcHUrRV2fLxC2uepRUSbvuTmufSgLaUiDK7gYNhhzQvTkPoB4l0hzr6RG9EZq4+w+HR9kRjjgrYkCo4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
